//
// This file is auto-generated by scripts/generate-sdk-version-header.js
// Do not edit manually. Update sdk-version.json instead.
//

#ifndef SDK_VERSION_H
#define SDK_VERSION_H

static const int SDK_VERSION = 20260119;

#endif /* SDK_VERSION_H */
